# Aplicación
spring.application.name=siplanilla-backend
server.port=8080
server.servlet.context-path=/api

# Perfil activo por defecto (Railway sobreescribe con SPRING_PROFILES_ACTIVE=prod)
# spring.profiles.active=dev

# JPA / Hibernate (común)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration
jwt.secret=mySecretKeyForJwtTokenGenerationAndValidationPurposeOnly123456789SecretKeyMustBeAtLeast32CharactersLongForHS512
jwt.expiration=86400000

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=siplanilla.sistema@gmail.com
spring.mail.password=srmr trxa fvlb sbmj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Desbloqueo de Cuenta
app.desbloqueo.max-intentos=3
app.desbloqueo.token-expiration-minutes=15

# Frontend URL
app.frontend.url=http://localhost:4200
